# Generated by Django 4.2.4 on 2023-09-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='email_check_status',
            field=models.CharField(choices=[('Check failed', 'failed'), ('Check failed', 'in_progress'), ('Check failed', 'passed')], default='in_progress'),
        ),
    ]
