# Generated by Django 4.2.4 on 2023-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_signupinfo_email_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='is_signup_finished',
            field=models.BooleanField(default=False),
        ),
    ]
