# Generated by Django 4.2.4 on 2023-09-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_signupinfo_is_signup_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupinfo',
            name='email_check_status',
            field=models.CharField(choices=[('Check failed', 'failed'), ('Check in progress', 'in_progress'), ('Check success', 'passed')], default='in_progress'),
        ),
    ]
