# Generated by Django 4.2.4 on 2023-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_publisher_remove_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
